server:
  port: 8000
builder:
  sourceDir: client
  targetDir: public
  files:
    client.js:
      - classes/*.js
      - main.js
    index.html: pages/index.js
    blog.html: pages/blog.js
    about.html: pages/about.js
